name: Custom Build

on:
  workflow_dispatch:
    inputs:
      planName:
        description: 'buildPlans.IosevkaBababoi'
        required: true
        default: 'IosevkaBababoi'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: iosevka

      - name: 安装 Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: iosevka/package-lock.json

      - name: 安装 ttfautohint
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ttfautohint

      - name: 构建字体
        working-directory: iosevka
        run: |
          npm install
          npm run build -- ttf,woff2::${{ github.event.inputs.planName }}

      - name: 上传字体成品
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.planName }}
          path: iosevka/dist/${{ github.event.inputs.planName }}/
