name: Custom Build

on:
  workflow_dispatch:
    inputs:
      planName:
        description: 'IosevkaBababoi'
        required: true
        default: 'IosevkaBababoi'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build -- ttf,woff2::${{ github.event.inputs.planName }}
      - name: IosevkaBababoi
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.planName }}
          path: dist/${{ github.event.inputs.planName }}/
